name: Build and Release Zip

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build and Release Zip
      run: |
        RELEASE_VERSION=$(echo "${GITHUB_REF#refs/tags/}")
        echo "Release version: $RELEASE_VERSION"
        zip -r "$RELEASE_VERSION.zip" brro-webdev/ -x "*.git*"
        mv "$RELEASE_VERSION.zip" "./$RELEASE_VERSION.zip"
        echo "Zip file created: $RELEASE_VERSION.zip"
