name: Build and Release Zip

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Zip
      run: zip -r ${GITHUB_REF#refs/tags/}.zip brro-webdev/ -x "*.git*"
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${GITHUB_REF#refs/tags/}.zip
        asset_name: ${GITHUB_REF#refs/tags/}.zip
        asset_content_type: application/zip
