name: Build and Release WP Zip File

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Release Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Print Release Version
      run: echo $RELEASE_VERSION
    - name: Build Zip
      run: zip -r $GITHUB_WORKSPACE/$RELEASE_VERSION.zip brro-webdev/ -x "*.git*"
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: $GITHUB_WORKSPACE/$RELEASE_VERSION.zip
        asset_name: $RELEASE_VERSION.zip
        asset_content_type: application/zip
